### ISSUE TITLE
access_token

### ISSUE THREAD

**Issue by mathieu** [artifex404/grav-plugin-instagram#1]
It seems one needs a access_token now to get access to instagram api : 
https://www.instagram.com/developer/endpoints/users/#get_users_media_recent_self

**Comment by artifex404** [comment]
It is still working with user_id & client_id. This might be another way of retrieving the feed. I'll have a look at it.

**Comment by artifex404** [comment]
Fixed in v1.1.0.

**Comment by mathieu** [comment]
works fine :-) thanks
