### ISSUE TITLE
How to use variables inside instagram_feed()?

### ISSUE THREAD

**Issue by Sogl** [artifex404/grav-plugin-instagram#10]
Hi!

I'm trying to implement custom template with this plugin. When I put `{{ instagram_feed() }}` into my twig, I see output of my `templates/partials/instagram.html.twig`.

But how to pass some `page.header` variables and other parameters to this function and use it inside `instagram.html.twig`?

**Comment by artifex404** [comment]
If you don't need those variables in the Instagram loop, you could just wrap your instagram block into your own .twig template and pass all the needed variables to it.

The function `instagram_feed()` single purpose is to just display the feed.

If you really need, you can customize the plugin and pass your needed variables here: https://github.com/artifex404/grav-plugin-instagram/blob/master/instagram.php#L99

**Comment by Sogl** [comment]
Simple `{% include 'partials/instagram.html.twig' %}` don't work.

Here I see that function expect parameters: https://github.com/artifex404/grav-plugin-instagram/blob/master/instagram.php#L58
but this variable is not used. Why?

**Comment by artifex404** [comment]
Please refer to PHP and twig documentation. Closing this issue as it is not related to the plugin functionality.

**Comment by Sogl** [comment]
This is what I needed: https://github.com/artifex404/grav-plugin-instagram/pull/11
