### ISSUE TITLE
Page not found error with twig

### ISSUE THREAD

**Issue by bbricker87** [artifex404/grav-plugin-instagram#5]
Great plugin! Worked very well after one change. I'm not sure if this is an issue with just me or not. I installed this plugin through the admin. I was getting a "page not found" error on this line `{{ instagram_feed() }}` in my twig file.

I ended up going into the instagram.php file in the plugin and changing line 84 from this

`$url = 'https://api.instagram.com/v1/users/'` **. $config->get('feed_parameters.user_id') .** `'/media/recent/?access_token=' . $config->get('feed_parameters.access_token');`

to this

`$url = 'https://api.instagram.com/v1/users/`**self**`/media/recent/?access_token=' . $config->get('feed_parameters.access_token');`

That's how I made the call on a Wordpress site I made a couple years back, and it still worked. The only thing is that the user_id doesn't matter using this method.

Just thought I would bring to attention if anyone else was dealing with issues with this.

**Comment by artifex404** [comment]
Thanks Ben for reporting! Will give this change a try, and will implement if the user id is really not needed. You could contribute by making a pull request for this change.

**Comment by artifex404** [comment]
Thanks for the pull request! Closing this issue.

**Comment by julienvanderkluft** [comment]
Hi,

I had the same error after installing the plugin via Grav CLI, and this fix still works. But package doesn't look updated 🤔

Anyway, thanks for this plugin.

**Comment by artifex404** [comment]
@julienvanderkluft Made the release. This fix should be soon available through Grav CLI.

**Comment by julienvanderkluft** [comment]
@artifex404 Updated, works well 👍

**Comment by artifex404** [comment]
Great stuff. Thanks for reporting!
