### ISSUE TITLE
Wrong max count in blueprint

### ISSUE THREAD

**Issue by jimblue** [artifex404/grav-plugin-instagram#8]
Hi,

Actually the instagram API only return 20 images per call.
Because of this even if you put count field to 100 you'll get only 20 pictures back.

For better usage of your plugin it would be better to document this and change the max count value in the blueprint:
https://github.com/artifex404/grav-plugin-instagram/blob/e72f41a17a50ec4787789064ed9d590cb9264822/blueprints.yaml#L43

An other solution is to make as many call as needed to get the desire count number, 20 images per 20 images, then cache the result.

Thank you

**Comment by artifex404** [comment]
This has been implemented in the latest version. Thanks!
